local Worker = require('___plugin_name___.kit.Lua.Worker')

describe('kit.Lua.Worker', function()
  it('should work basic usage', function()
    vim.pretty_print('start')
    local worker = Worker.new(function()
      require('___plugin_name___.kit.IO').walk('./fixture', function(entry)
        print(entry.path)
      end):sync()
    end)
    worker:run():sync()
    vim.pretty_print('finish')
  end)
end)
