local System = require('___kit___.kit.System')

describe('kit.System', function()
  describe('LineBuffering', function()
    it('should buffering by line', function()
      local count = 0
      local buffer = System.LineBuffering.new({ ignore_empty = true }):create(function(text)
        count = count + 1
        assert.are.equals(text, tostring(count))
      end)
      buffer.write('1\n')
      buffer.write('\n')
      buffer.write('2')
      buffer.write('\n3')
      buffer.close()
      assert.are.equals(count, 3)
    end)
  end)
  describe('DelimiterBuffering', function()
    it('should buffering by delimiter', function()
      local consumed = {}
      local buffer = System.DelimiterBuffering.new({ delimiter = '\t\t\t' }):create(function(text)
        table.insert(consumed, text)
      end)
      buffer.write('1')
      buffer.write('\t\t\t2\t\t\t3')
      buffer.write('\t\t\t')
      buffer.write('4')
      buffer.write('\t\t\t5')
      buffer.write('\t\t6\t\t\t')
      buffer.write('7')
      buffer.close()
      assert.are.same(consumed, { '1', '2', '3', '4', '5\t\t6', '7' })
    end)
  end)
end)
